// ============================================================================
// MODULE: hdmi_top
// DESCRIPTION: Configurable top-level for HDMI output.
// CLOCK NOTE: Based on the board clock, requires a clk_pixel and a clk_tmds(= 5*clk_pixel)
// On the Tang Nano 9K, these clocks must be generated by an rPLL module.
// ============================================================================

module hdmi_top #(
    // Horizontal parameters (Pixel)   | ACTIVE | FRONT | SYNC | BACK |
    parameter int H_ACTIVE   = 640,  
    parameter int H_FRONT    = 16,
    parameter int H_SYNC     = 96,
    parameter int H_BACK     = 48,
    parameter int H_TOTAL = H_ACTIVE + H_FRONT + H_SYNC + H_BACK,

    // Vertical Parameters (Lines)     | ACTIVE | FRONT | SYNC | BACK |    
    parameter int V_ACTIVE   = 480,
    parameter int V_FRONT    = 10,
    parameter int V_SYNC     = 2,
    parameter int V_BACK     = 33,
    parameter int V_TOTAL = V_ACTIVE + V_FRONT + V_SYNC + V_BACK,

    // Polarity
    parameter bit H_SYNC_POL = 1'b0,
    parameter bit V_SYNC_POL = 1'b0,

    // Needed bits to correct count pixels
    parameter int H_BITS = $clog2(H_TOTAL),
    parameter int V_BITS = $clog2(H_TOTAL)
)(
    input  logic rst_n,       // Asynchronous reset active low
    input  logic clk_27MHz,   // Pixel clk
    
   // Differential outputs (On the Tang Nano these are mapped to the TLVDS/LVCMOS33 pins)
    output logic tmds_clk_p,  output logic tmds_clk_n,
    output logic tmds_d0_p,   output logic tmds_d0_n,  // Blue
    output logic tmds_d1_p,   output logic tmds_d1_n,  // Green
    output logic tmds_d2_p,   output logic tmds_d2_n   // Red
);

    // --- Internal Signals ---
    logic clk_pixel;          // Pixel_clk
    logic clk_tmds;           // TMDS clock 5x 
    logic [H_BITS-1:0] cx;    //counter x
    logic [V_BITS-1:0] cy;    //counter y
    logic hsync, vsync, vde;
    logic [7:0] red, green, blue;
    logic [9:0] tmds_r, tmds_g, tmds_b;

    Gowin_rPLL PLL(
        .clkout(clk_tmds),     //output TMDS clock (pixel_clk * 5)  
        //.clkoutd(clk_pixel), //output pixel clock    
        .reset(~rst_n),        //input reset
        .clkin(clk_27MHz)      //input clkin   27 MHz
    );
    assign clk_pixel= clk_27MHz;

    // 1. Sincronisms Generator (Timings)
    video_timing #(
        .H_ACTIVE(H_ACTIVE), .H_FRONT(H_FRONT), .H_SYNC(H_SYNC), .H_BACK(H_BACK), .H_TOTAL(H_TOTAL), .H_SYNC_POL(H_SYNC_POL), .H_BITS(H_BITS),
        .V_ACTIVE(V_ACTIVE), .V_FRONT(V_FRONT), .V_SYNC(V_SYNC), .V_BACK(V_BACK), .V_TOTAL(V_TOTAL), .V_SYNC_POL(V_SYNC_POL), .V_BITS(V_BITS)
    ) timing_inst (
        .clk(clk_pixel),
        .rst_n(rst_n),
        .cx(cx),
        .cy(cy),
        .hsync(hsync),
        .vsync(vsync),
        .vde(vde)
    );

    /*// 2. Static Video Pattern Generator (Test pattern XOR)
    always_comb begin
        if (vde) begin
            red   = {cx[7:0]};              // Gradiente X
            green = {cy[7:0]};              // Gradiente Y
            blue  = cx[7:0] ^ cy[7:0];      // Pattern XOR
        end 
        else begin
            red = 8'h00; green = 8'h00; blue = 8'h00;
        end
    end
    */

    // 2. Dynamic Video Pattern Generator

    //"Logo" dimension (80×60-pixel rectangle)
    localparam int LOGO_W = 80;
    localparam int LOGO_H = 60;

    // Status registers: Position and Direction
    logic [9:0] logo_x;
    logic [9:0] logo_y;
    logic       dir_x; // 1 = move right, 0 = move left
    logic       dir_y; // 1 = move down,   0 = move up
    
    // A register to change the colour of the logo with every bounce
    logic [7:0] color_seed; 

    // PHYSICS ENGINE: Updates position only once per frame
    always_ff @(posedge clk_pixel or negedge rst_n) begin
        if (!rst_n) begin
            // Position and initial state
            logo_x     <= 10'd100;
            logo_y     <= 10'd100;
            dir_x      <= 1'b1;
            dir_y      <= 1'b1;
            color_seed <= 8'hFF; 
        end 
        else if (cx == 0 && cy == 0) begin
            // ------------------------------------------------
            // Horizontal axis (X)
            // ------------------------------------------------
            if (dir_x == 1'b1) begin
                // I'm moving right. Have I hit the right edge?
                if (logo_x + LOGO_W >= H_ACTIVE - 1) begin
                    dir_x <= 1'b0; // Reverse direction (left)
                    color_seed <= color_seed + 8'h33; // Change colour
                end else begin
                    logo_x <= logo_x + 10'd2; // Speed: 2 pixels per frame
                end
            end else begin
                // I'm moving left. Have I touched the left edge?
                if (logo_x <= 1) begin
                    dir_x <= 1'b1; // Reverse direction (right)
                    color_seed <= color_seed + 8'h55;
                end else begin
                    logo_x <= logo_x - 10'd2;
                end
            end

            // ------------------------------------------------
            // Vertical axis (Y)
            // ------------------------------------------------
            if (dir_y == 1'b1) begin
                // I'm going down. Have I hit the bottom?
                if (logo_y + LOGO_H >= V_ACTIVE - 1) begin
                    dir_y <= 1'b0; // Reverse direction (up)
                    color_seed <= color_seed + 8'h77;
                end else begin
                    logo_y <= logo_y + 10'd2;
                end
            end else begin
                // I'm going up. Have I reached the top?
                if (logo_y <= 1) begin
                    dir_y <= 1'b1; // Reverse direction (down)
                    color_seed <= color_seed + 8'h99;
                end else begin
                    logo_y <= logo_y - 10'd2;
                end
            end
        end
    end

    // RENDERER: Is the current pixel (cx, cy) INSIDE the logo?
    logic is_logo;
    assign is_logo = (cx >= logo_x) && (cx < logo_x + LOGO_W) && 
                     (cy >= logo_y) && (cy < logo_y + LOGO_H);

    // COLOR MUX
    always_comb begin
        if (vde) begin
            if (is_logo) begin
                // Draw the movable rectangle 
                red   = color_seed;
                green = ~color_seed;
                blue  = {color_seed[3:0], color_seed[7:4]};
            end else begin
                // Dark background (dark blue)
                red   = 8'h00;
                green = 8'h00;
                blue  = 8'h1A;
            end
        end 
        else begin
            // Blanket area
            red = 8'h00; green = 8'h00; blue = 8'h00;
        end
    end

    // 3. Encoder TMDS (3 channels)
    // The BLU channel (D0) carries HSYNC and VSYNC during blanking (vde=0)
    tmds_encoder enc_b (.clk(clk_pixel), .rst_n(rst_n), .data_in(blue),  .ctrl({vsync, hsync}), .vde(vde), .tmds_out(tmds_b));
    tmds_encoder enc_g (.clk(clk_pixel), .rst_n(rst_n), .data_in(green), .ctrl(2'b00),          .vde(vde), .tmds_out(tmds_g));
    tmds_encoder enc_r (.clk(clk_pixel), .rst_n(rst_n), .data_in(red),   .ctrl(2'b00),          .vde(vde), .tmds_out(tmds_r));

    // 4. Serializer 10:1 
    logic s_clk, s_d0, s_d1, s_d2;

    serializer_10to1 ser_b   (.rst_n(rst_n), .clk_pixel(clk_pixel), .clk_tmds(clk_tmds), .data_in(tmds_b),     .serial_out(s_d0));
    serializer_10to1 ser_g   (.rst_n(rst_n), .clk_pixel(clk_pixel), .clk_tmds(clk_tmds), .data_in(tmds_g),     .serial_out(s_d1));
    serializer_10to1 ser_r   (.rst_n(rst_n), .clk_pixel(clk_pixel), .clk_tmds(clk_tmds), .data_in(tmds_r),     .serial_out(s_d2));
    serializer_10to1 ser_clk (.rst_n(rst_n), .clk_pixel(clk_pixel), .clk_tmds(clk_tmds), .data_in(10'b1111100000), .serial_out(s_clk));

    // The ELVDS_OBUF primitive is required to generate real differential hardware
    ELVDS_OBUF obuf_d0 (
    .I (s_d0),
    .O (tmds_d0_p),
    .OB(tmds_d0_n)
    );

    ELVDS_OBUF obuf_d1 (
    .I (s_d1),
    .O (tmds_d1_p),
    .OB(tmds_d1_n)
    );

    ELVDS_OBUF obuf_d2 (
    .I (s_d2),
    .O (tmds_d2_p),
    .OB(tmds_d2_n)
    );

    ELVDS_OBUF obuf_clk (
    .I (s_clk),
    .O (tmds_clk_p),
    .OB(tmds_clk_n)
    );

endmodule
