# =============================================================================
# FILE: test_hdmi_framebuffer_capture.py
#
# DESCRIZIONE:
#   The parser does not capture the serialised HDMI image, but reads directly the contents of the internal framebuffer, 
#   that is the RAM containing the RGB332 pixels of the 160x120 frame.
#
#   The test:
#     1. generates the clock;
#     2. applies a reset;
#     3. waits for the framebuffer to be written to at least once;
#     4. synchronises at the start of a frame;
#     5. reads directly from the simulated BRAM;
#     6. writes HEX/CSV files containing the cell contents.
# =============================================================================

import csv     #Used to generate a .csv file that can be opened in Excel 
import cocotb  # allows to manipulate hardware signals from Python

from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, Timer
from cocotb.utils import get_sim_time


# =============================================================================
# DESIGN PARAMETERS
# =============================================================================

H_ACTIVE = 640
V_ACTIVE = 480
SCALE = 4

#logic framebuffer
FB_WIDTH = H_ACTIVE // SCALE          # 160
FB_HEIGHT = V_ACTIVE // SCALE         # 120
FRAME_SIZE = FB_WIDTH * FB_HEIGHT     # 19200

# expected value
EXPECTED_RED = 0xE0


# =============================================================================
# TEST CONFIGURATION
# =============================================================================

CLK_PERIOD_NS = 40 # The clock generated by Cocotb has a period of 40 ns -> f=25 MHz

RESET_TIME_US = 1 # Hold the reset pin low for 1 us, then releases it

# If True, after detecting that the RAM has been filled at least once,
# wait for the next frame start (cx=0, cy=0).
WAIT_FRAME_START_BEFORE_CAPTURE = True

# At 640×480, a full frame is 800×525 = 420,000 cycles.
TIMEOUT_CYCLES = 2_000_000  # tiemout safety limit

#During long waits, the parser displays a progress message every 50,000 cycles
PROGRESS_LOG_EVERY = 50_000


# =============================================================================
# UTILITY
# =============================================================================

def safe_int(value, default=0): 
    """
    Converts a Cocotb value to an integer.
    If the value contains X/Z/U, returns the default value.
    """
    try:
        if value.is_resolvable:
            return int(value)
    except Exception:
        pass

    return default


async def wait_cycles(clk, cycles):
    """
    Waits for a specific number of clock cycles.
    """
    for _ in range(cycles):
        await RisingEdge(clk)


def get_dbg_clk(dut):
    """
    This function selects which clock to use as a reference

    If `dbg_clk_pixel` exists in top, it uses that.
    If it does not exist, it uses `clk_27MHz` as a fallback.
    """
    if hasattr(dut, "dbg_clk_pixel"):
        return dut.dbg_clk_pixel

    return dut.clk_27MHz


def get_cx(dut):
    """
    Reads cx using the debug port first; 
    if that is not available, it uses the internal signal
    """
    if hasattr(dut, "dbg_cx"):
        return safe_int(dut.dbg_cx.value)

    return safe_int(dut.cx.value)


def get_cy(dut):
    """
    Reads cy using the debug port first; 
    if that is not available, it uses the internal signal
    """
    if hasattr(dut, "dbg_cy"):
        return safe_int(dut.dbg_cy.value)

    return safe_int(dut.cy.value)


def get_wr_ptr(dut):
    """
    Reads the internal write pointer of the framebuffer pipeline.
    """
    try:
        return safe_int(dut.fb_pipeline.wr_ptr.value)
    except Exception as exc:
        raise RuntimeError(
            "Unable to read dut.fb_pipeline.wr_ptr. "
        ) from exc


def read_memory_cell(dut, addr):
    """
    Reads a cell from the simulated BRAM memory.

    Hierarchy expected:
        hdmi_top
          fb_pipeline
            fb
              ram
                mem[addr]

    Returns an integer value between 0 and 255.
    """
    try:
        value = dut.fb_pipeline.fb.ram.mem[addr].value
        return safe_int(value)
    except Exception as exc:
        raise RuntimeError(
            f"Unable to read dut.fb_pipeline.fb.ram.mem[{addr}]."
            "The expected hierarchy is: fb_pipeline.fb.ram.mem."
        ) from exc


async def wait_framebuffer_written_once(dut, clk):
    """
    This function waits for the framebuffer to be filled at least once.

    Logic:
      - After a reset, wr_ptr starts at 0;
      - Wait for it to become non-zero;
      - Wait for it to return to 0;
      - When it returns to 0, the writer has crossed FRAME_SIZE cells.
    """
    dut._log.info("Waits for the framebuffer to be filled at least once...")

    seen_nonzero = False    # Don't consider the reset to zero valid until I've seen wr_ptr change 

    for cycle in range(TIMEOUT_CYCLES):
        await RisingEdge(clk)

        wr_ptr = get_wr_ptr(dut)

        if wr_ptr != 0:
            seen_nonzero = True     # When `wr_ptr` becomes non-zero, means that the writer has started writing

        if seen_nonzero and wr_ptr == 0:
            dut._log.info(
                f"The framebuffer has been written to at least once in the last {cycle} cycles."
            )
            return

        if cycle % PROGRESS_LOG_EVERY == 0:
            cx = get_cx(dut)
            cy = get_cy(dut)
            sim_time_ns = get_sim_time(unit="ns")

            dut._log.info(
                f"Progress fill: cycle={cycle}, sim_time={sim_time_ns} ns, "
                f"cx={cx}, cy={cy}, wr_ptr={wr_ptr}"
            )

    raise TimeoutError(
        "Timeout: wr_ptr has not been reset to zero."
        "The framebuffer may not have been written correctly."
    )


async def wait_frame_start(dut, clk):
    """
    Wait for the start of the next video frame, cx=0 and cy=0.

    Note:
      At 640x480, a full frame requires 800*525 = 420,000 cycles.
      With Icarus, this can take a significant amount of real-time.
    """
    dut._log.info("Waiting for the start of the video frame: cx=0, cy=0...")

    # Avoid detecting the same moment immediately if we are already at 0,0
    await RisingEdge(clk)

    for cycle in range(TIMEOUT_CYCLES):
        await RisingEdge(clk)

        cx = get_cx(dut)
        cy = get_cy(dut)

        if cx == 0 and cy == 0:
            sim_time_ns = get_sim_time(unit="ns")
            dut._log.info(
                f"Start of frame detected after {cycle} cycles, "
                f"sim_time={sim_time_ns} ns."
            )
            return

        if cycle % PROGRESS_LOG_EVERY == 0:
            sim_time_ns = get_sim_time(unit="ns")
            dut._log.info(
                f"Progress frame wait: cycle={cycle}, sim_time={sim_time_ns} ns, "
                f"cx={cx}, cy={cy}"
            )

    raise TimeoutError(
        "Timeout: start of frame cx=0, cy=0 not detected."
    )


def capture_framebuffer_from_memory(dut):
    """
    Reads the entire 160x120 framebuffer from internal memory.

    Returns a matrix:
        fb[y][x] = RGB332 pixel, integer 0..255
    """
    fb = [
        [0 for _ in range(FB_WIDTH)]
        for _ in range(FB_HEIGHT)
    ]

    for y in range(FB_HEIGHT):
        for x in range(FB_WIDTH):
            addr = y * FB_WIDTH + x
            fb[y][x] = read_memory_cell(dut, addr)

    return fb


def save_hex_matrix(fb, filename):
    """
    Save the framebuffer as a 160x120 HEX array.
    """
    with open(filename, "w", encoding="utf-8") as f:
        for y in range(FB_HEIGHT):
            line = " ".join(f"{fb[y][x]:02X}" for x in range(FB_WIDTH))
            f.write(line + "\n")


def save_hex_linear(fb, filename):
    """
    Save the framebuffer in linear format, one pixel per row.

    Raster-scan order:
        addr = y * FB_WIDTH + x
    """
    with open(filename, "w", encoding="utf-8") as f:
        for y in range(FB_HEIGHT):
            for x in range(FB_WIDTH):
                f.write(f"{fb[y][x]:02X}\n")


def save_cells_csv(fb, filename):
    """
    Save the framebuffer as a CSV file containing the address, coordinates and HEX value.

    Format:
        addr,x,y,hex
        0,0,0,E0
        1,1,0,E0
        ...
    """
    with open(filename, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["addr", "x", "y", "hex"])

        for y in range(FB_HEIGHT):
            for x in range(FB_WIDTH):
                addr = y * FB_WIDTH + x
                writer.writerow([addr, x, y, f"{fb[y][x]:02X}"])


def count_values(fb):
    """
    Count the distribution of RGB332 values in the framebuffer.
    """
    counts = {}

    for y in range(FB_HEIGHT):
        for x in range(FB_WIDTH):
            value = fb[y][x]
            counts[value] = counts.get(value, 0) + 1

    return counts


def save_report(counts, filename):
    """
    Generates a text report of the capture.
    """
    total_pixels = FB_WIDTH * FB_HEIGHT
    red_pixels = counts.get(EXPECTED_RED, 0)

    with open(filename, "w", encoding="utf-8") as f:
        f.write("Framebuffer capture report\n")
        f.write("==========================\n\n")
        f.write(f"FB_WIDTH     = {FB_WIDTH}\n")
        f.write(f"FB_HEIGHT    = {FB_HEIGHT}\n")
        f.write(f"FRAME_SIZE   = {FRAME_SIZE}\n")
        f.write(f"Total pixels = {total_pixels}\n\n")

        f.write("Value distribution:\n")
        for value, count in sorted(counts.items()):
            f.write(f"0x{value:02X}: {count}\n")

        f.write("\n")
        f.write(f"Expected RED value = 0x{EXPECTED_RED:02X}\n")
        f.write(f"RED pixels         = {red_pixels}/{total_pixels}\n")

        if red_pixels == total_pixels:
            f.write("Result             = OK, framebuffer completely red\n")
        else:
            f.write("Result             = WARNING, framebuffer not completely red\n")


# =============================================================================
# MAIN TEST
# =============================================================================

@cocotb.test()
async def capture_framebuffer_frame(dut):
    """
    Main test Cocotb.
    """
    dut._log.info("============================================================")
    dut._log.info("START FRAMEBUFFER FRAME CAPTURE")
    dut._log.info("============================================================")

    # -------------------------------------------------------------------------
    # Clock
    # -------------------------------------------------------------------------
    cocotb.start_soon(
        Clock(dut.clk_27MHz, CLK_PERIOD_NS, unit="ns").start()  # Cocotb generates a clock on clk_27MHz of T=CLK_PERIOD_NS
    )

    # -------------------------------------------------------------------------
    # Reset design
    # -------------------------------------------------------------------------
    dut.rst_n.value = 0   # The reset is active low
    await Timer(RESET_TIME_US, unit="us")

    dut.rst_n.value = 1   # Release reset
    await Timer(RESET_TIME_US, unit="us")

    dut._log.info("Reset completed.")

    clk = get_dbg_clk(dut)  # the parser selects which clock to use

    #  settling-in periods  (dummy)
    await wait_cycles(clk, 20)

    dut._log.info("Clock pixel/debug active.")

    # -------------------------------------------------------------------------
    # Waiting for the framebuffer to be filled
    # -------------------------------------------------------------------------
    await wait_framebuffer_written_once(dut, clk)

    # -------------------------------------------------------------------------
    # Frame synchronisation
    # -------------------------------------------------------------------------
    if WAIT_FRAME_START_BEFORE_CAPTURE:
        await wait_frame_start(dut, clk)

    # -------------------------------------------------------------------------
    # Snapshot BRAM
    # -------------------------------------------------------------------------
    sim_time_ns = get_sim_time(unit="ns")
    cx = get_cx(dut)
    cy = get_cy(dut)

    dut._log.info(
        f"Capture a framebuffer snapshot at sim_time={sim_time_ns} ns, "
        f"cx={cx}, cy={cy}."
    )

    fb = capture_framebuffer_from_memory(dut)  # Reading all RAM cells

    # -------------------------------------------------------------------------
    # Save file and counting values
    # -------------------------------------------------------------------------
    matrix_file = "framebuffer_160x120_matrix.hex"
    linear_file = "framebuffer_160x120_linear.hex"
    csv_file    = "framebuffer_160x120_cells.csv"
    report_file = "framebuffer_capture_report.txt"

    save_hex_matrix(fb, matrix_file)
    save_hex_linear(fb, linear_file)
    save_cells_csv(fb, csv_file)

    counts = count_values(fb)
    save_report(counts, report_file)

    dut._log.info(f"File written: {matrix_file}")
    dut._log.info(f"File written: {linear_file}")
    dut._log.info(f"File written: {csv_file}")
    dut._log.info(f"File written: {report_file}")

    # -------------------------------------------------------------------------
    # Value distribution 
    # -------------------------------------------------------------------------
    dut._log.info("Distribution of RGB332 values in the framebuffer:")

    for value, count in sorted(counts.items()):
        dut._log.info(f"0x{value:02X}: {count} pixel")

    total_pixels = FB_WIDTH * FB_HEIGHT
    red_pixels = counts.get(EXPECTED_RED, 0)

    dut._log.info(f"Red pixel 0x{EXPECTED_RED:02X}: {red_pixels}/{total_pixels}")

    if red_pixels == total_pixels:  # Red screen check
        dut._log.info("OK: The framebuffer is completely red.")
    else:
        dut._log.warning(
            "ERROR: The framebuffer is not completely red. "
        )

    dut._log.info("============================================================")
    dut._log.info("END FRAMEBUFFER FRAME CAPTURE")
    dut._log.info("============================================================")